### ISSUE TITLE
when install groot error : AttributeError: module 'mhelper' has no attribute 'Logger'

### ISSUE THREAD

**Issue by ChoiHyeonJu** [BehaviorTree/Groot#147]
I installing groot and execute it.
when i write a $ groot and get a error

If anyone knows the answer to this error, please let me know.
please!!

choi@choi:~/Groot/build$ groot
Traceback (most recent call last):
  File "/home/choi/.local/bin/groot", line 5, in <module>
    from groot.__main__ import main
  File "/home/choi/.local/lib/python3.8/site-packages/groot/__init__.py", line 5, in <module>
    from groot.application import *
  File "/home/choi/.local/lib/python3.8/site-packages/groot/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/choi/.local/lib/python3.8/site-packages/groot/application/application.py", line 5, in <module>
    import intermake
  File "/home/choi/.local/lib/python3.8/site-packages/intermake/__init__.py", line 5, in <module>
    from intermake.engine.environment import run_jupyter, Application, acquire, start
  File "/home/choi/.local/lib/python3.8/site-packages/intermake/engine/__init__.py", line 1, in <module>
    from .local_data import _LocalData
  File "/home/choi/.local/lib/python3.8/site-packages/intermake/engine/local_data.py", line 16, in <module>
    _LOG = mh.Logger( "autostore", False )
AttributeError: module 'mhelper' has no attribute 'Logger'

**Comment by ChoiHyeonJu** [comment]
i solve it! thank you

**Comment by romanhaa** [comment]
@ChoiHyeonJu how did you solve it?

**Comment by alansaji360** [comment]
@ChoiHyeonJu Wanted to bump this thread and ask if you remember how you were able to rectify the AttributeError, Thanks!
